version: '3'

services:
  orders-db:
    image: postgres:16.2
    container_name: orders_database
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
