version: '3'

services:
  orders-db:
    image: postgres:15.3
    container_name: orders-database
    restart: always
    ports:
      - 5434:5433
    environment:
      - POSTGRES_USER=orders
      - POSTGRES_PASSWORD=orders
      - POSTGRES_DB=ordersdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
